name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        run: cargo build --release --target=x86_64-pc-windows-msvc
